#pragma once
//**************************************
// lex.h
//
// Defines global symbols used the the flex generated lexer and 
// bison generated parser.
//
// Author: Phil Howard phil.howard@oit.edu
//

#include "cSymbol.h"
#include "langparse.h"
#include "cAstNode.h"

// lexer function generated by flex
int yylex();

typedef union
{
    int token;
    cSymbol *symbol;
} yylval_t;


int yyparse();                          // parsing function
int yylex();                            // scanning function
extern char *yytext;                    // text of current token
extern int yylineno;                    // line number of input file
extern int yynerrs;                     // Num of compile errors
extern FILE *yyin;                      // FILE pointer for input
extern cAstNode *yyast_root;            // root of AST
extern int g_insert;        // global to indicate that symbols should be 
                            // inserted into the symbol table
extern int g_local;         // global to indicate to do local lookups
